# Generated by Django 2.2.16 on 2022-04-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220331_2123'),
        ('posts', '0008_auto_20220401_0126'),
        ('posts', '0006_comment'),
    ]

    operations = [
    ]
